on:
  pull_request:
    types: [ labeled ]

jobs:
  download_strings:
    if: ${{ github.event.label.name == 'pull-easytranslate-strings' }}
    runs-on: ubuntu-latest
    name: Download strings from EasyTranslate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Execute our action
        uses: ./
        id: pull_easytranslate
        with:
          easytranslate_action: 'pull'
          source_language: 'en'
          source_root_folder: 'resources'
          translation_file_paths: 'files/**/**json'
          target_languages: 'da,de'
          access_token: ${{ secrets.EASYTRANSLATE_API_ACCESS_TOKEN }}
          base_api_url: 'https://api.platform.testing.easytranslate.com'
          team_name: 'x-force-deadpool'
          string_library_id: '62bdd58660666d016074a805'

      - name: Update the pull request
        if: steps.pull_easytranslate.outputs.outcome === 'continue'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config user.name 'Stefan Brankovik'
          git config user.email 'stefan.brankovik@gmail.com'
          git add .
          git commit -am 'Updating strings'
          git push
