on: [ push ]

jobs:
  download_strings:
    runs-on: ubuntu-latest
    name: Download strings from EasyTranslate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute our action
        uses: ./
        id: hello
        with:
          easytranslate_action: 'pull'
          source_language: 'en'
          source_root_folder: 'resources'
          translation_file_paths: 'files/**/**json'
          target_languages: 'da,de'
          access_token: ${{ secrets.EASYTRANSLATE_API_ACCESS_TOKEN }}
          base_api_url: 'https://api.platform.testing.easytranslate.com'
          team_name: 'x-force-deadpool'
          string_library_id: '62bdd58660666d016074a805'

      - name: Prepare for pull request
        run: |
          git config user.name 'Stefan Brankovik'
          git config user.email 'stefan.brankovik@gmail.com'
          git checkout -b stefan/strings-update
          git add .
          git commit -am 'Updating strings'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          base: main
          branch-suffix: timestamp